import "./globals.css";
import BlogLayout from './BlogLayout'

export const metadata = {
  title: 'Demo of ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html className='light' lang="en">

      <body className='bg-transparent dark:bg-gray-900'>

        <BlogLayout>
          {children}
        </BlogLayout>
      </body>

    </html>

  )
}
